name: 'Auto Repo Sync'
description: 'This Action enables you to synchronize code to other code management platforms, such as GitLab, Bitbucket, etc.'

branding:
  icon: 'upload-cloud'
  color: 'gray-dark'

inputs:
  target-url:
    description: 'Target repository URL, e.g., https://github.com/<user>/<repo>.git'
    required: true
  target-username:
    description: 'Target Repository Username.'
    required: true
  target-token:
    description: 'Personal Access Token for Authentication.'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/offensive-vk/auto-repo-sync:latest'
  env:
    INPUT_TARGET_URL: ${{ inputs.target-url }}
    INPUT_TARGET_USERNAME: ${{ inputs.target-username }}
    INPUT_TARGET_TOKEN: ${{ inputs.target-token }}
