name: 'Auto Repo Sync'
description: 'Auto Repo Sync enables you to synchronize code to other code management platforms, such as GitLab, Bitbucket, etc.'

branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  target-url:
    description: 'Target Repo URL'
    required: true
  target-username:
    description: 'Target Repo Username'
    required: true
  target-token:
    description: 'Target Token'
    required: true

runs:
  using: "composite"
  steps:
    - run: chmod 755 ./entrypoint.sh; ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.target-url }}
        INPUT_TARGET_USERNAME: ${{ inputs.target-username }}
        INPUT_TARGET_TOKEN: ${{ inputs.target-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
