name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-repo-sync"
      description: "Synchronize Your Git Repository to other VCS Platforms like Gitlab, Bitbucket, etc."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}