name: CI / Mirror Sync

on:
  workflow_call:
    secrets:
      target-url:
        description: "Target repository URL"
        required: true
      target-username:
        description: "Username for the target repository"
        required: true
      target-token:
        description: "Token for the target repository"
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync
        uses: ./
        with:
          target-url: ${{ secrets.target-url }}
          target-username: ${{ secrets.target-username }}
          target-token: ${{ secrets.target-token }}
