name: CI / Test Action

on:
  push: 
    branches: ["**"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Sync
      uses: ./
      with:
        target-url: ${{ secrets.TARGET_URL }}
        target-username: ${{ secrets.TARGET_USERNAME }}
        target-token: ${{ secrets.TARGET_TOKEN }}
